// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://douryjhcgunzcluabpkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdXJ5amhjZ3VuemNsdWFicGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDIwNzYsImV4cCI6MjA2NjU3ODA3Nn0.CX0s1hX-f0D3MPe55HeiSPShZfHMMkILT8A07cLrZFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);